(function(){'use strict';
var API_BASE=location.origin,PAGE_SIZE=50,CONCURRENCY=5,RETRY_MAX=30,RETRY_INTERVAL=500,retryCount=0;function getQpu(){var v=parseInt(localStorage.getItem('quota_per_unit'));return v>0?v:500000;}
function log(m){console.log('[YZ]',m);}log('v1.3');
function getUserId(){try{var u=JSON.parse(localStorage.getItem('user'));return u?String(u.id):null;}catch(e){return null;}}
function findButton(t){var bs=document.querySelectorAll('button');for(var i=0;i<bs.length;i++){if((bs[i].textContent||'').trim()===t)return bs[i];}return null;}
function tryInject(){
var q=findButton('查询'),r=findButton('重置');if(!q||!r)return false;
var c=q.parentElement;if(!c||document.getElementById('yunzhou-export-btn'))return true;
var b=document.createElement('button');b.id='yunzhou-export-btn';b.className=q.className;b.type='button';
b.innerHTML='<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" style="vertical-align:middle;margin-right:4px"><path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>导出账单';
b.title='导出使用日志为 CSV';b.style.cssText='margin-left:8px;';
b.addEventListener('click',showExportDialog);c.appendChild(b);log('injected');return true;}
function scheduleInjection(){if(tryInject())return;retryCount++;if(retryCount<RETRY_MAX)setTimeout(scheduleInjection,RETRY_INTERVAL);else log('gave up');}
var lastUrl=location.href;new MutationObserver(function(){if(location.href!==lastUrl){lastUrl=location.href;retryCount=0;scheduleInjection();}}).observe(document.querySelector('title')||document.body,{subtree:true,childList:true});
var dObs=new MutationObserver(function(){if(tryInject())dObs.disconnect();});if(document.body)dObs.observe(document.body,{childList:true,subtree:true});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){dObs.observe(document.body,{childList:true,subtree:true});scheduleInjection();});else scheduleInjection();
function showExportDialog(){if(document.getElementById("yzd"))return;var m=document.createElement("div");m.id="yzd";m.style.cssText="position:fixed;top:0;left:0;width:100%;height:100%;background:rgba(0,0,0,.5);z-index:99999;display:flex;align-items:center;justify-content:center;font-family:system-ui,sans-serif;";m.innerHTML="<div style='background:#fff;border-radius:12px;padding:24px 28px;box-shadow:0 8px 40px rgba(0,0,0,.25);min-width:420px;max-width:520px;color:#1a1a2e;'><div style='font-size:18px;font-weight:700;margin-bottom:20px;display:flex;align-items:center;gap:8px;'><svg width='20' height='20' viewBox='0 0 24 24' fill='none' stroke='#667eea' stroke-width='2'><path d='M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4'/><polyline points='7 10 12 15 17 10'/><line x1='12' y1='15' x2='12' y2='3'/></svg>导出账单</div><div style='display:grid;grid-template-columns:80px 1fr;gap:12px 10px;align-items:center;font-size:14px;'><label>开始时间</label><input id='yzds' type='datetime-local' value='2026-05-20T00:00' style='padding:6px 10px;border:1px solid #ddd;border-radius:6px;font-size:13px;'/><label>结束时间</label><input id='yzde' type='datetime-local' value='2026-05-20T23:59' style='padding:6px 10px;border:1px solid #ddd;border-radius:6px;font-size:13px;'/><label>令牌名称</label><input id='yztn' placeholder='全部（留空）' style='padding:6px 10px;border:1px solid #ddd;border-radius:6px;font-size:13px;'/><label>分组</label><input id='yzgr' placeholder='全部（留空）' style='padding:6px 10px;border:1px solid #ddd;border-radius:6px;font-size:13px;'/><label>类型</label><select id='yztp' style='padding:6px 10px;border:1px solid #ddd;border-radius:6px;font-size:13px;'><option value='0'>全部</option><option value='2'>消费</option><option value='1'>充值</option></select><label>模型名称</label><input id='yzmn' placeholder='全部（留空）' style='padding:6px 10px;border:1px solid #ddd;border-radius:6px;font-size:13px;'/></div><div style='margin-top:20px;display:flex;justify-content:flex-end;gap:10px;'><button id='yzcancel' style='padding:8px 20px;border:1px solid #ddd;border-radius:8px;background:#fff;cursor:pointer;font-size:14px;'>取消</button><button id='yzdo' style='padding:8px 24px;border:none;border-radius:8px;background:linear-gradient(135deg,#667eea,#764ba2);color:#fff;cursor:pointer;font-size:14px;font-weight:600;'>导出 CSV</button></div></div>";document.body.appendChild(m);document.getElementById("yzcancel").onclick=function(){m.remove();};document.getElementById("yzdo").onclick=function(){m.remove();doExport();};}
function readDialogFilters(){var el=function(id){var e=document.getElementById(id);return e?e.value.trim():'';};var s=el('yzds'),e=el('yzde');var ts=function(s){if(!s)return 0;var d=new Date(s);return isNaN(d.getTime())?0:Math.floor(d.getTime()/1000);};return{type:parseInt(el('yztp'))||0,start_timestamp:ts(s),end_timestamp:ts(e)||Math.floor(Date.now()/1000),token_name:el('yztn'),model_name:el('yzmn'),group:el('yzgr'),request_id:''};}
var overlay=null;function showP(m){if(!overlay){overlay=document.createElement('div');overlay.id='yzeo';overlay.style.cssText='position:fixed;top:0;left:0;width:100%;height:100%;background:rgba(0,0,0,.45);z-index:99999;display:flex;align-items:center;justify-content:center;font-family:system-ui,sans-serif;';overlay.innerHTML='<div style="background:#fff;border-radius:12px;padding:32px 48px;text-align:center;box-shadow:0 8px 32px rgba(0,0,0,.18);min-width:320px;"><div style="font-size:16px;font-weight:600;margin-bottom:16px;color:#1a1a2e;" id="yzt">\u6b63\u5728\u5bfc\u51fa...</div><div style="width:100%;height:6px;background:#e8e8e8;border-radius:3px;overflow:hidden;"><div id="yzb" style="height:100%;background:linear-gradient(90deg,#667eea,#764ba2);border-radius:3px;transition:width .3s;width:0%;"></div></div><div style="margin-top:12px;font-size:13px;color:#666;" id="yzp">\u51c6\u5907\u4e2d...</div></div>';document.body.appendChild(overlay);}document.getElementById('yzp').textContent=m;}
function upP(c,t){var p=t>0?Math.round(c/t*100):0;var b=document.getElementById('yzb');if(b)b.style.width=p+'%';showP('\u5df2\u83b7\u53d6 '+c+' / '+t+' \u9875');}
function hideP(){if(overlay){overlay.remove();overlay=null;}}
function buildUrl(f,pg){var p=new URLSearchParams();p.set("p",pg);p.set("page_size",PAGE_SIZE);p.set("type",f.type);p.set("token_name",f.token_name);p.set("model_name",f.model_name);p.set("start_timestamp",f.start_timestamp);p.set("end_timestamp",f.end_timestamp);p.set("group",f.group);p.set("request_id",f.request_id);return API_BASE+"/api/log/self?"+p.toString();}
function fetchPage(url){var h={};var uid=getUserId();if(uid)h["New-Api-User"]=uid;return fetch(url,{credentials:"include",headers:h}).then(function(r){if(!r.ok)throw new Error("HTTP "+r.status);return r.json();}).then(function(j){if(!j.success)throw new Error(j.message||"API error");return j.data;});}
function fetchAll(f){return fetchPage(buildUrl(f,1)).then(function(d){var items=d.items.slice();if(d.total===0)return items;var tp=Math.ceil(d.total/PAGE_SIZE);if(tp<=1)return items;upP(1,tp);var pages=[];for(var p=2;p<=tp;p++)pages.push(p);function fb(i){if(i>=pages.length)return Promise.resolve();var b=pages.slice(i,i+CONCURRENCY);return Promise.all(b.map(function(p){return fetchPage(buildUrl(f,p));})).then(function(rs){rs.forEach(function(r){items.push.apply(items,r.items);});upP(i+b.length+1,tp);return fb(i+CONCURRENCY);});}return fb(0).then(function(){return items;});});}
function parseO(s){if(!s)return{};try{var o=JSON.parse(s);return o||{};}catch(e){return{};}}
function fmtT(ts){var d=new Date(ts*1000);var p=function(n){return String(n).padStart(2,"0");};return d.getFullYear()+"-"+p(d.getMonth()+1)+"-"+p(d.getDate())+" "+p(d.getHours())+":"+p(d.getMinutes())+":"+p(d.getSeconds());}
function genCSV(items){var h=['\u65f6\u95f4','\u7528\u6237\u540d','\u4ee4\u724c\u540d\u79f0','\u5206\u7ec4','\u7c7b\u578b','\u6a21\u578b\u540d\u79f0','\u7528\u65f6(\u79d2)','\u6d41\u5f0f','\u8f93\u5165Token','\u8f93\u51faToken','\u7f13\u5b58Token','\u82b1\u8d39(USD)','\u6e20\u9053ID','\u5206\u7ec4\u500d\u7387','\u6a21\u578b\u500d\u7387','Request ID'];var esc=function(v){var s=String(v!=null?v:'');return(s.indexOf(',')!==-1||s.indexOf('"')!==-1||s.indexOf('\n')!==-1)?'"'+s.replace(/"/g,'""')+'"':s;};var rows=items.map(function(item){var o=parseO(item.other);return[fmtT(item.created_at),item.username,item.token_name,item.group,item.type===2?'\u6d88\u8d39':item.type===1?'\u5145\u503c':'\u5176\u4ed6',item.model_name,item.use_time,item.is_stream?'\u6d41\u5f0f':'\u975e\u6d41',item.prompt_tokens,item.completion_tokens,o.cache_tokens||0,(item.quota/getQpu()).toFixed(6),item.channel,o.group_ratio!=null?o.group_ratio:'',o.model_ratio!=null?o.model_ratio:'',item.request_id].map(esc).join(',');});return '\uFEFF'+h.join(',')+'\n'+rows.join('\n');}
function dlCSV(csv,fn){var b=new Blob([csv],{type:"text/csv;charset=utf-8;"});var u=URL.createObjectURL(b);var a=document.createElement("a");a.href=u;a.download=fn;document.body.appendChild(a);a.click();document.body.removeChild(a);URL.revokeObjectURL(u);}
function showToast(msg){var t=document.createElement('div');t.textContent=msg;t.style.cssText='position:fixed;top:20px;left:50%;transform:translateX(-50%);background:#1a1a2e;color:#fff;padding:12px 24px;border-radius:8px;font-size:14px;z-index:999999;box-shadow:0 4px 16px rgba(0,0,0,.2);animation:yf .3s ease;';document.body.appendChild(t);var s=document.createElement('style');s.textContent='@keyframes yf{from{opacity:0;transform:translateX(-50%) translateY(-8px)}to{opacity:1;transform:translateX(-50%) translateY(0)}}';document.head.appendChild(s);setTimeout(function(){t.remove();s.remove();},3000);}
function doExport(){var uid=getUserId();if(!uid){alert('\u65e0\u6cd5\u83b7\u53d6\u7528\u6237\u4fe1\u606f');return;}try{var f=readDialogFilters();showP('\u6b63\u5728\u83b7\u53d6...');fetchAll(f).then(function(items){if(!items.length){alert('\u65e0\u6570\u636e');hideP();return;}showP('\u751f\u6210CSV...');var csv=genCSV(items);var n=new Date();var ts=n.getFullYear()+String(n.getMonth()+1).padStart(2,'0')+String(n.getDate()).padStart(2,'0')+'_'+String(n.getHours()).padStart(2,'0')+String(n.getMinutes()).padStart(2,'0')+String(n.getSeconds()).padStart(2,'0');hideP();dlCSV(csv,'\u4e91\u821fAPI_\u4f7f\u7528\u65e5\u5fd7_'+ts+'.csv');showToast('\u5bfc\u51fa\u6210\u529f! '+items.length+' \u6761');}).catch(function(e){hideP();log(e);alert('\u5931\u8d25: '+e.message);});}catch(e){hideP();log(e);alert('\u5931\u8d25: '+e.message);}}
})();